# Generated by Django 5.2 on 2025-04-29 00:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apt', models.CharField(max_length=10)),
                ('nome', models.CharField(max_length=100)),
                ('fotos', models.ImageField(blank=True, upload_to='entregas/%Y/%m/')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('receberam', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('ocorrencia', models.TextField(blank=True)),
                ('nomeResp', models.CharField(max_length=200)),
            ],
        ),
    ]
